package gt.dvdyzag.gui;

import gt.dvdyzag.db.PostgreSQL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author David Y. Gonzalez <a href="mailto:dvdyzag@gmail.com">dvdyzag@gmail.com</a>
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jbConectar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpUserInput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfURL = new javax.swing.JTextField();
        jlPuerto = new javax.swing.JLabel();
        jtfContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNombreUsuario = new javax.swing.JTextField();
        jsPuerto = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jtfNombreBD = new javax.swing.JTextField();
        jlURLOK = new javax.swing.JLabel();
        jlNombreBDOK = new javax.swing.JLabel();
        jlNombreUsuario = new javax.swing.JLabel();
        jlContrasena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jbConectar.setText("Conectar");
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 5;
        jPanel1.add(jbConectar, gridBagConstraints);

        jbLimpiar.setText("Limpiar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 5;
        jPanel1.add(jbLimpiar, gridBagConstraints);

        jLabel5.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Listo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 4);
        jPanel1.add(jLabel6, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jpUserInput.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Nombre Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jpUserInput.add(jLabel2, gridBagConstraints);

        jtfURL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfURL.setText("localhost");
        jtfURL.setPreferredSize(new java.awt.Dimension(96, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jtfURL, gridBagConstraints);

        jlPuerto.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jpUserInput.add(jlPuerto, gridBagConstraints);

        jtfContrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfContrasena.setText("foo.bar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jtfContrasena, gridBagConstraints);

        jLabel1.setText("Conección URL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jpUserInput.add(jLabel1, gridBagConstraints);

        jLabel4.setText("# Puerto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jpUserInput.add(jLabel4, gridBagConstraints);

        jtfNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNombreUsuario.setText("postgres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jtfNombreUsuario, gridBagConstraints);

        jsPuerto.setValue(5432);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jsPuerto, gridBagConstraints);

        jLabel3.setText("Nombre Base Datos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jpUserInput.add(jLabel3, gridBagConstraints);

        jtfNombreBD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNombreBD.setText("tienda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jtfNombreBD, gridBagConstraints);

        jlURLOK.setText("OK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jpUserInput.add(jlURLOK, gridBagConstraints);

        jlNombreBDOK.setText("OK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jpUserInput.add(jlNombreBDOK, gridBagConstraints);

        jlNombreUsuario.setText("OK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jpUserInput.add(jlNombreUsuario, gridBagConstraints);

        jlContrasena.setText("OK");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jpUserInput.add(jlContrasena, gridBagConstraints);

        getContentPane().add(jpUserInput, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed
        PostgreSQL psql = new PostgreSQL(jtfURL.getText(), 
                (Integer)jsPuerto.getValue(), 
                jtfNombreBD.getText(), 
                jtfNombreUsuario.getText(), 
                String.valueOf(jtfContrasena.getPassword()));
        try {
            psql.connDB();
        } catch (SQLException ex) {
            System.out.println("some sort of sqlexception");
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbConectarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbConectar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JLabel jlContrasena;
    private javax.swing.JLabel jlNombreBDOK;
    private javax.swing.JLabel jlNombreUsuario;
    private javax.swing.JLabel jlPuerto;
    private javax.swing.JLabel jlURLOK;
    private javax.swing.JPanel jpUserInput;
    private javax.swing.JSpinner jsPuerto;
    private javax.swing.JPasswordField jtfContrasena;
    private javax.swing.JTextField jtfNombreBD;
    private javax.swing.JTextField jtfNombreUsuario;
    private javax.swing.JTextField jtfURL;
    // End of variables declaration//GEN-END:variables
}
