package gt.dvdyzag.gui;

import gt.dvdyzag.db.PostgreSQL;
import gt.dvdyzag.db.objetos.Tabla;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Y. Gonzalez <a href="mailto:dvdyzag@gmail.com">dvdyzag@gmail.com</a>
 */
public class Principal extends javax.swing.JFrame {

    private PostgreSQL psql;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jp1 = new javax.swing.JPanel();
        jpUserInput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfURL = new javax.swing.JTextField();
        jlPuerto = new javax.swing.JLabel();
        jtfContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNombreUsuario = new javax.swing.JTextField();
        jsPuerto = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jtfNombreBD = new javax.swing.JTextField();
        jpControl1 = new javax.swing.JPanel();
        jbConectar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jlMsgConn = new javax.swing.JLabel();
        jlTitulo1 = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlTablas = new javax.swing.JList();
        jpControl2 = new javax.swing.JPanel();
        jbAceptarTabla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtColumnas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Normalizer");

        jp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jp1.setLayout(new java.awt.BorderLayout());

        jpUserInput.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Nombre Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jpUserInput.add(jLabel2, gridBagConstraints);

        jtfURL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfURL.setText("localhost");
        jtfURL.setPreferredSize(new java.awt.Dimension(96, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jtfURL, gridBagConstraints);

        jlPuerto.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jpUserInput.add(jlPuerto, gridBagConstraints);

        jtfContrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfContrasena.setText("foo.bar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jtfContrasena, gridBagConstraints);

        jLabel1.setText("Conección URL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jpUserInput.add(jLabel1, gridBagConstraints);

        jLabel4.setText("# Puerto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jpUserInput.add(jLabel4, gridBagConstraints);

        jtfNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNombreUsuario.setText("postgres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jtfNombreUsuario, gridBagConstraints);

        jsPuerto.setValue(5432);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jsPuerto, gridBagConstraints);

        jLabel3.setText("Nombre Base Datos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jpUserInput.add(jLabel3, gridBagConstraints);

        jtfNombreBD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNombreBD.setText("tienda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 2;
        jpUserInput.add(jtfNombreBD, gridBagConstraints);

        jp1.add(jpUserInput, java.awt.BorderLayout.CENTER);

        jpControl1.setLayout(new java.awt.GridBagLayout());

        jbConectar.setText("Conectar");
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 5;
        jpControl1.add(jbConectar, gridBagConstraints);

        jLabel5.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jpControl1.add(jLabel5, gridBagConstraints);

        jlMsgConn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlMsgConn.setText("Listo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 4);
        jpControl1.add(jlMsgConn, gridBagConstraints);

        jp1.add(jpControl1, java.awt.BorderLayout.SOUTH);

        jlTitulo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo1.setText("Datos de la conexión DB PostgreSQL");
        jlTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jp1.add(jlTitulo1, java.awt.BorderLayout.NORTH);

        jp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jp2.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Elija una Tabla");
        jp2.add(jLabel6, java.awt.BorderLayout.NORTH);

        jlTablas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlTablas);

        jp2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jpControl2.setLayout(new java.awt.BorderLayout());

        jbAceptarTabla.setText("Aceptar Tabla");
        jbAceptarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarTablaActionPerformed(evt);
            }
        });
        jpControl2.add(jbAceptarTabla, java.awt.BorderLayout.LINE_END);

        jp2.add(jpControl2, java.awt.BorderLayout.SOUTH);

        jtColumnas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Null", "Longitud maxima", "Precisión numérica"
            }
        ));
        jScrollPane2.setViewportView(jtColumnas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed
        psql = new PostgreSQL(jtfURL.getText(), 
                (Integer)jsPuerto.getValue(), 
                jtfNombreBD.getText(), 
                jtfNombreUsuario.getText(), 
                String.valueOf(jtfContrasena.getPassword()));
                jlMsgConn.setText("Conectado a " + psql.getDbName());
        try {
            psql.connDB();
            ResultSet rs = psql.runQuery(PostgreSQL.consultaTablas);
            // http://stackoverflow.com/questions/12134823/displaying-data-from-database-in-jlist
            DefaultListModel<String> dlm = new DefaultListModel<>();
            while (rs.next()) {
                dlm.addElement(rs.getString("table_name"));
            }
            jlTablas.setModel(dlm);
        } catch (SQLException | ClassNotFoundException ex) {
            jlMsgConn.setText("ha ocurrido un error");
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbConectarActionPerformed

    private void jbAceptarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarTablaActionPerformed
        String tabla = (String)jlTablas.getSelectedValue();
        if (tabla == null){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado tabla alguna", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            DefaultTableModel dtm = (DefaultTableModel) jtColumnas.getModel();
            dtm.setRowCount(0);
            Tabla t = new Tabla(tabla, psql);
            ResultSet rs = t.getRs();
            while(rs.next()){
                dtm.insertRow(jtColumnas.getRowCount(), new Object[]{
                    rs.getString("column_name"),
                    rs.getString("data_type"),
                    rs.getString("is_nullable"),
                    rs.getString("max_length"),
                    rs.getString("precision")
                });
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbAceptarTablaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAceptarTabla;
    private javax.swing.JButton jbConectar;
    private javax.swing.JLabel jlMsgConn;
    private javax.swing.JLabel jlPuerto;
    private javax.swing.JList jlTablas;
    private javax.swing.JLabel jlTitulo1;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jpControl1;
    private javax.swing.JPanel jpControl2;
    private javax.swing.JPanel jpUserInput;
    private javax.swing.JSpinner jsPuerto;
    private javax.swing.JTable jtColumnas;
    private javax.swing.JPasswordField jtfContrasena;
    private javax.swing.JTextField jtfNombreBD;
    private javax.swing.JTextField jtfNombreUsuario;
    private javax.swing.JTextField jtfURL;
    // End of variables declaration//GEN-END:variables
}
